---
deployment:
  tasks:
    - export DEPLOYPATH=/home/liveiptvnow
    - /bin/cp -rf * $DEPLOYPATH/
    - /bin/rm -f $DEPLOYPATH/bootstrap/cache/*.php 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/storage/framework/views/*.php 2>/dev/null || true
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache 2>/dev/null || true
